
name: 'chess'
version: '1.0.0'
config-version: 2


profile: 'default'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]


target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"


models:
  chess:
    staging:
      +materialized: view
      +schema: staging
    interdiate:
      +materialized: ephemeral
    marts:
      +materialized: table
      +schema: marts


seeds:
  +schema: seeds